"""automigration

Revision ID: 36f905d910c2
Revises: f5a7878b1e83
Create Date: 2025-06-15 21:33:23.903922

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from sqlmodel import SQLModel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36f905d910c2"
down_revision: Union[str, None] = "f5a7878b1e83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
