"""empty message

Revision ID: 39b1f61c695e
Revises: 8bdc275622c9
Create Date: 2025-06-16 02:05:29.033939

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from sqlmodel import SQLModel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39b1f61c695e"
down_revision: Union[str, None] = "8bdc275622c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "prediction_requests",
        "limit_balance",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "prediction_requests", "sex", existing_type=sa.VARCHAR(length=6), nullable=True
    )
    op.alter_column(
        "prediction_requests",
        "education_level",
        existing_type=sa.VARCHAR(length=15),
        nullable=True,
    )
    op.alter_column(
        "prediction_requests",
        "marital_status",
        existing_type=sa.VARCHAR(length=7),
        nullable=True,
    )
    op.alter_column(
        "prediction_requests", "age", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "prediction_requests", "created_at", existing_type=sa.DATETIME(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "prediction_requests", "created_at", existing_type=sa.DATETIME(), nullable=False
    )
    op.alter_column(
        "prediction_requests", "age", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "prediction_requests",
        "marital_status",
        existing_type=sa.VARCHAR(length=7),
        nullable=False,
    )
    op.alter_column(
        "prediction_requests",
        "education_level",
        existing_type=sa.VARCHAR(length=15),
        nullable=False,
    )
    op.alter_column(
        "prediction_requests", "sex", existing_type=sa.VARCHAR(length=6), nullable=False
    )
    op.alter_column(
        "prediction_requests",
        "limit_balance",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###
