"""empty message

Revision ID: 423d1288dd13
Revises: 9087989c4d45
Create Date: 2025-06-16 02:22:23.369671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlmodel import SQLModel


# revision identifiers, used by Alembic.
revision: str = '423d1288dd13'
down_revision: Union[str, None] = '9087989c4d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('limit_balance', sa.Integer(), nullable=True),
    sa.Column('sex', sa.Enum('male', 'female', name='sexenum'), nullable=True),
    sa.Column('education_level', sa.Enum('graduate_school', 'high_school', 'university', 'others', 'unknown', name='educationlevelenum'), nullable=True),
    sa.Column('marital_status', sa.Enum('single', 'married', 'others', 'unknown', name='maritalstatusenum'), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('prediction_request')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction_request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('limit_balance', sa.INTEGER(), nullable=True),
    sa.Column('sex', sa.VARCHAR(length=6), nullable=True),
    sa.Column('education_level', sa.VARCHAR(length=15), nullable=True),
    sa.Column('marital_status', sa.VARCHAR(length=7), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('prediction_requests')
    # ### end Alembic commands ###
