"""empty message

Revision ID: 9087989c4d45
Revises: 0b68d2b86f15
Create Date: 2025-06-16 02:10:02.168315

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from sqlmodel import SQLModel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9087989c4d45"
down_revision: Union[str, None] = "0b68d2b86f15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
