"""automigration

Revision ID: b2c075a1ef9f
Revises: fd668366a00f
Create Date: 2025-06-15 20:24:05.575016

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from sqlmodel import SQLModel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2c075a1ef9f"
down_revision: Union[str, None] = "fd668366a00f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "predictionrequest",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("limit_balance", sa.Integer(), nullable=False),
        sa.Column("sex", sa.Enum("male", "female", name="sexenum"), nullable=False),
        sa.Column(
            "education_level",
            sa.Enum(
                "graduate_school",
                "high_school",
                "university",
                "others",
                "unknown",
                name="educationlevelenum",
            ),
            nullable=False,
        ),
        sa.Column(
            "marital_status",
            sa.Enum("single", "married", "others", "unknown", name="maritalstatusenum"),
            nullable=False,
        ),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("predictionrequest")
    # ### end Alembic commands ###
